apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-deployment
spec:
  selector:
    matchLabels:
      app: date
  template:
    metadata:
      labels:
        app: date
    spec:
      containers:
        - name: date
          image: prj-pf24dev-docker.artifacts.mms-at-work.de/crse/skaffold/date
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
